[workspace]
members = [
    "asynchronous",
    "builder-pattern",
    "logging", "middleware", "middleware02",
    "monitor01",
    "trait01",
    "trait02-marker-traits",
    "trait03-dynamic-dispatch"
]

resolver = "2"
