[package]
name = "monitor01"
version = "0.1.0"
edition = "2021"

[dependencies]
prometheus = "0.13.4"
tokio = { version = "1.40.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
